# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - name: Installing Packages 🥁
        run: yarn install

      - name: Building 🧱
        run: yarn build
        env:
          NEXT_PUBLIC_TRACKING_ID: G-8FBXBFXC10
          NEXT_PUBLIC_SERVICE_ID: service_qt4ryip
          NEXT_PUBLIC_TEMPLATE_ID: template_2ni69n8
          NEXT_PUBLIC_USER_ID: user_Do31sKneP4eYfn5n1nLTD

      - name: Exporting Bundle Files 🎪
        run: yarn export
      - run: touch ./out/.nojekyll

      - name: Deploy to Github-Pages 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: out # The folder the action should deploy.
